[package]
name = "jabber_core"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.64"
tree-sitter = "0.24.3"
tree-sitter-jabber = { path = "../../tree-sitter-jabber"}

[build-dependencies]
cc = "*"
