[package]
name = "jabber_core"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.64"
tree-sitter-jabber = { path = "../../tree-sitter-jabber"}
type-sitter = { version = "0.5.0", default-features = false }

[build-dependencies]
cc = "*"
type-sitter-gen = "0.5.0"
