[package]
name = "jabber_core"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.64"
tree-sitter = "^0.22.2" # required by type-sitter-gen
tree-sitter-jabber = { path = "../../tree-sitter-jabber"}
type-sitter-lib = { version = "0.4.0", default-features = false }

[build-dependencies]
cc = "*"
type-sitter-gen = "0.4.0"
